from ..data_method import date_to_int64, write_bool, write_int32, write_int64


def write_infobase(infobase, packet):
    packet.append_raw(infobase['infobase'].bytes)
    packet.append_raw(write_int32(infobase['date_offset']))
    packet.append(infobase['dbms'].encode())
    packet.append(infobase['db_name'].encode())
    packet.append(infobase['db_password'])
    packet.append(infobase['db_server_name'].encode())
    packet.append(infobase['db_user'].encode())
    packet.append_raw(write_int64(date_to_int64(infobase['denied_from'])))
    packet.append(infobase['denied_message'].encode())
    packet.append(infobase['denied_parameter'].encode())
    packet.append_raw(write_int64(date_to_int64(infobase['denied_to'])))
    packet.append(infobase['descr'].encode())
    packet.append(infobase['locale'].encode())
    packet.append(infobase['name'].encode())
    packet.append(infobase['permission_code'].encode())
    packet.append_raw(write_bool(infobase['scheduled_jobs_denied']))
    packet.append_raw(write_int32(infobase['security_level']))
    packet.append_raw(write_bool(infobase['sessions_denied']))
    packet.append_raw(write_int32(infobase['license_distribution']))
    packet.append(infobase['external_connection_string'].encode())
    packet.append_raw(write_bool(infobase['external_session_manager_required']))
    packet.append(infobase['securirty_profile'].encode())
    packet.append(infobase['safe_mode_securirty_profile'].encode())
    packet.append_raw(write_bool(infobase['reserve_working_processes']))
